spring.application.name=savat

spring.datasource.url=jdbc:mariadb://localhost:3306/sav_at
spring.datasource.username=root
spring.datasource.password=alexander
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false
app.jwt.secret=savat-clave-secreta-super-larga-para-firmar-tokens-jwt-2026-cambiar-en-produccion
app.jwt.expiration-ms=86400000

app.cors.allowed-origin=http://localhost:4200